### ISSUE TITLE
是否考虑集成在youtube-dl?

### ISSUE THREAD

**Issue by loopArray** [lvqier/crawlers#2]
偶然看到这个库真感叹作者好强大的分析加密技术的能力，能够写出QQ视频的下载加密方法。我在用youtube-dl的时候发现不支持QQ视频，不知道作者有没有时间给youtube-dl写个扩展插件。这样会有更多人去维护。不知道作者觉得怎么样？

**Comment by zhangn1985** [comment]
try https://github.com/zhangn1985/ykdl 也是支持腾讯视频。

**Comment by loopArray** [comment]
@zhangn1985 果然可以呀，我本来以为必须要先计算出ckey才能获取含有各种格式的xml信息，没想到你的方法里也可以获取，你是怎么发现的？

**Comment by zhangn1985** [comment]
偶然。

Ckey是没啥用的。

**Comment by loopArray** [comment]
O(∩_∩)O哈哈~， 送你一朵大红花。❀
我又可以愉快的收藏电影了。

**Comment by zhangn1985** [comment]
enjoy yourself
